"""Shared metadata and column helpers for the Postgres schema.

SQLAlchemy Core rather than the ORM: the existing services are written as
queries, not object graphs, and Core keeps them that way while still giving
Alembic something to autogenerate from.

Two conventions run through every table:

* ``id`` is a UUID generated by the application (see :mod:`app.ids`), with a
  server-side default as a safety net for rows inserted by hand or by a
  migration.
* Any table that hangs off a user carries ``user_id`` even when it could be
  reached by joining upward. Row-level security policies read it directly, and
  a composite foreign key keeps it honest — see ``owned_by`` below.
"""

from __future__ import annotations

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKeyConstraint,
    MetaData,
    text,
)
from sqlalchemy.dialects.postgresql import UUID

# Explicit naming so Alembic emits stable, readable constraint names instead of
# letting Postgres invent them — otherwise a downgrade cannot find what to drop.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


def pk_column() -> Column:
    """Primary key. gen_random_uuid() is builtin from Postgres 13 (pgcrypto)."""
    return Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at() -> Column:
    return Column(
        "created_at",
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )


def updated_at() -> Column:
    return Column(
        "updated_at",
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )


def timestamps() -> tuple[Column, Column]:
    return created_at(), updated_at()


def owned_by(parent: str, *, column: str, ondelete: str = "CASCADE"):
    """A composite foreign key that pins a child to its parent *and* its owner.

    ``jobs.user_id`` exists so RLS never has to join upward, but a plain foreign
    key would allow it to disagree with ``profiles.user_id`` — a job filed under
    someone else's profile. Referencing the parent's ``(id, user_id)`` pair makes
    that unrepresentable, with no trigger to maintain.

    The parent must carry ``UniqueConstraint("id", "user_id")`` for this to
    resolve; every owning table below does.
    """
    return ForeignKeyConstraint(
        [column, "user_id"],
        [f"{parent}.id", f"{parent}.user_id"],
        ondelete=ondelete,
    )
