"""Add generated title

Revision ID: 874680572750
Revises: 17825c65bb13
Create Date: 2026-08-19 01:28:09.296396+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '874680572750'
down_revision = '17825c65bb13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "extraction_runs",
        sa.Column("generated_title", sa.Text(), server_default=sa.text("''"), nullable=False),
    )

    # Autogenerate cannot see a changed CHECK body -- it compares column types
    # and constraint names, not expressions -- so widening the prompt kinds is
    # written out by hand. Drop and recreate; Postgres has no ALTER CHECK.
    op.drop_constraint("kind_known", "prompts", type_="check")
    op.create_check_constraint(
        "kind_known", "prompts", "kind IN ('skills', 'tailoring', 'summary', 'title')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("kind_known", "prompts", type_="check")
    op.create_check_constraint(
        "kind_known", "prompts", "kind IN ('skills', 'tailoring', 'summary')"
    )
    op.drop_column("extraction_runs", "generated_title")
