"""Add jobs.skills

Revision ID: 17825c65bb13
Revises: 0001_initial_schema
Create Date: 2026-08-18 23:23:45.762917+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '17825c65bb13'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 0001_initial_schema derives its DDL from live model metadata, so on a
    # database built from scratch today it already includes every column
    # ever added since -- this one included. Guard the add so replaying the
    # full chain on a fresh database doesn't collide with what 0001 already
    # created; on the databases that predate 0001 (where this migration is
    # what actually added the column) it behaves exactly as before.
    bind = op.get_bind()
    existing = {c["name"] for c in sa.inspect(bind).get_columns("jobs")}
    if "skills" not in existing:
        op.add_column('jobs', sa.Column('skills', sa.Text(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'skills')
    # ### end Alembic commands ###
