"""Add jobs.skills

Revision ID: 17825c65bb13
Revises: 0001_initial_schema
Create Date: 2026-08-18 23:23:45.762917+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '17825c65bb13'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('skills', sa.Text(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'skills')
    # ### end Alembic commands ###
