"""Add generated title

Revision ID: 874680572750
Revises: 17825c65bb13
Create Date: 2026-08-19 01:28:09.296396+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '874680572750'
down_revision = '17825c65bb13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # See the matching comment in 20260818_2323_add_jobs_skills.py: guard
    # against 0001_initial_schema having already created this column on a
    # database built from scratch.
    bind = op.get_bind()
    existing = {c["name"] for c in sa.inspect(bind).get_columns("extraction_runs")}
    if "generated_title" not in existing:
        op.add_column(
            "extraction_runs",
            sa.Column("generated_title", sa.Text(), server_default=sa.text("''"), nullable=False),
        )

    # Autogenerate cannot see a changed CHECK body -- it compares column types
    # and constraint names, not expressions -- so widening the prompt kinds is
    # written out by hand. Drop and recreate; Postgres has no ALTER CHECK.
    op.drop_constraint("kind_known", "prompts", type_="check")
    op.create_check_constraint(
        "kind_known", "prompts", "kind IN ('skills', 'tailoring', 'summary', 'title')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("kind_known", "prompts", type_="check")
    op.create_check_constraint(
        "kind_known", "prompts", "kind IN ('skills', 'tailoring', 'summary')"
    )
    op.drop_column("extraction_runs", "generated_title")
